spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/reporeader}
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.embedding.model=text-embedding-3-small

spring.security.oauth2.client.registration.github.client-id=Ov23liOxElDVOH2FGK42
spring.security.oauth2.client.registration.github.secret=b79b128cf99e806d1aa6ba113ced6efa415bb29d
spring.security.oauth2.client.registration.github.scope=read:user,repo
spring.security.oauth2.client.provider.github.user-name-attribute=id

server.servlet.session.cookie.name=READREPO_SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=Lax
server.servlet.session.timeout=7d

app.frontend-url=http://localhost:3000
app.cors.allowed-origin=http://localhost:3000
app.token-encryption-password=local-encryption-key
app.token-encryption-salt=$2a$12$iquyyyJAlA9nZwlGo0CYK.J37Qn.to/0mTtiCspNAyO8778006XZG
app.indexing.max-file-bytes=102400
app.indexing.chunk-size=800
app.indexing.chunk-overlap=100
app.github.api-delay-ms=50

spring.main.allow-circular-references=true   